#!/bin/sh

mkdir -p opk
cp ./PokeMini opk/PokeMini
cp ../../resource/pokemini.png opk/icon.png
cp ../../LICENSE opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=PokeMini
Comment=Pokemon Mini emulator
Exec=PokeMini %f
Icon=icon
Terminal=false
Type=Application
selectorfilter=.min
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rs90.desktop

mksquashfs ./opk pokemini_rs90_rg99.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
